# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by device/samsung/gtel3g/setup-makefiles.sh

$(call inherit-product, vendor/samsung/gtel3g/gtel3g-vendor-blobs.mk)
