# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gtel3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gtel3g/proprietary/bin/phoneserver:system/vendor/bin/phoneserver \
    vendor/samsung/gtel3g/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/gtel3g/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/gtel3g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gtel3g/proprietary/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gtel3g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gtel3g/proprietary/etc/wifi/nvram_mfg.txt:system/vendor/etc/wifi/nvram_mfg.txt \
    vendor/samsung/gtel3g/proprietary/etc/wifi/nvram_net.txt:system/vendor/etc/wifi/nvram_net.txt \
    vendor/samsung/gtel3g/proprietary/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/camera.vendor.sc8830.so:system/vendor/lib/hw/camera.vendor.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/sensors.vendor.sc8830.so:system/vendor/lib/hw/sensors.vendor.sc8830.so \
    vendor/samsung/gtel3g/proprietary/lib/libboost.so:system/vendor/lib/libboost.so \
    vendor/samsung/gtel3g/proprietary/lib/libisp.so:system/vendor/lib/libisp.so \
    vendor/samsung/gtel3g/proprietary/lib/libmorpho_easy_hdr.so:system/vendor/lib/libmorpho_easy_hdr.so \
    vendor/samsung/gtel3g/proprietary/lib/libreference-ril_sp.so:system/vendor/lib/libreference-ril_sp.so \
    vendor/samsung/gtel3g/proprietary/lib/libuvdenoise.so:system/vendor/lib/libuvdenoise.so \
    vendor/samsung/gtel3g/proprietary/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd:system/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd

# Legacy SCX30G proprietary blobs
PRODUCT_COPY_FILES += \
    vendor/samsung/gtel3g/proprietary/bin/gpsd:system/vendor/bin/gpsd \
    vendor/samsung/gtel3g/proprietary/bin/gps.cer:system/vendor/bin/gps.cer \
    vendor/samsung/gtel3g/proprietary/lib/libsprd_agps_agent.so:system/vendor/lib/libsprd_agps_agent.so \
    vendor/samsung/gtel3g/proprietary/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so \
    vendor/samsung/gtel3g/proprietary/lib/libfactoryutil.so:system/vendor/lib/libfactoryutil.so \
    vendor/samsung/gtel3g/proprietary/lib/libatparser.so:system/vendor/lib/libatparser.so \
    vendor/samsung/gtel3g/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    vendor/samsung/gtel3g/proprietary/bin/macloader:system/vendor/bin/macloader \
    vendor/samsung/gtel3g/proprietary/bin/nvitemd:system/vendor/bin/nvitemd \
    vendor/samsung/gtel3g/proprietary/bin/refnotify:system/vendor/bin/refnotify \
    vendor/samsung/gtel3g/proprietary/bin/at_distributor:system/vendor/bin/at_distributor \
    vendor/samsung/gtel3g/proprietary/bin/engpc:system/vendor/bin/engpc \
    vendor/samsung/gtel3g/proprietary/bin/ext_data.sh:system/vendor/bin/ext_data.sh \
    vendor/samsung/gtel3g/proprietary/bin/ext_kill.sh:system/vendor/bin/ext_kill.sh \
    vendor/samsung/gtel3g/proprietary/bin/ext_symlink.sh:system/vendor/bin/ext_symlink.sh \
    vendor/samsung/gtel3g/proprietary/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/gtel3g/proprietary/lib/libomission_avoidance.so:system/vendor/lib/libomission_avoidance.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_aacdec_sprd.so:system/vendor/lib/libomx_aacdec_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_mp3dec_sprd.so:system/vendor/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/vendor/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/vendor/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/vendor/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/vendor/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/gtel3g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/vendor/lib/libomx_m4vh263enc_hw_sprd.so
